apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-springboot
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus-springboot
  endpoints:
  - port: http-traffic
    path: "/actuator/prometheus"
